
name: Kneba-Kernel Builder

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup env
        run: pacman -Sy --noconfirm git bc inetutils python3 flex bison libc++ libxml2 python-pip zip wget cpio jdk-openjdk tzdata && python3 -m pip install networkx && pip3 install --upgrade gupload
      - name: Build Kernel
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          KERNEL_DEFCONFIG: ${{ secrets.KERNEL_DEFCONFIG }}
          DEVICE_CODENAME: ${{ secrets.DEVICE_CODENAME }}
          ANYKERNEL: ${{ secrets.ANYKERNEL }}
        run: |
          export token=${TG_TOKEN}
          export git=${TOKEN}
          export TZ=Europe/Moscow
          bash build.sh
