
name: Kneba-Kernel Builder

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        run: pacman -Sy --noconfirm sudo && sudo pacman -Sy --noconfirm base-devel bc bison ccache jdk-openjdk ncurses libelf python ca-certificates curl flex clang gcc git wget zip zstd make openssl tzdata
      - name: Build Kernel
        env:
          TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          KERNEL_DEFCONFIG: ${{ secrets.KERNEL_DEFCONFIG }}
          DEVICE_CODENAME: ${{ secrets.DEVICE_CODENAME }}
          ANYKERNEL: ${{ secrets.ANYKERNEL }}
          AWAL: ${{ secrets.AWAL }}
          AKHIR: ${{ secrets.AKHIR }}
        run: |
          export token=${TG_TOKEN}
          export git=${TOKEN}
          export TZ=Asia/Jakarta
          bash build.sh
